name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3
      
      - name: Deploy to Server 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/alterra-agmc
            git pull origin/main
            git status
            cd day10
            sudo go mod tidy
            sudo go build main.go
            ./main
